@d7
@demo
# Some steps in this test set requires access to the API via drush.
# Note, non-standard themes etc may cause these assumptions to fail!
Feature: DrupalContext
  In order to ensure the testing connections are working
  As a tester
  I need to prove that behat testing works.

  @api
  Scenario: Create and log in as a (autogenerated) user
    Given I am logged in as a user with the "authenticated user" role
    #When I click "My account"
    When I visit "/user"
    And I click "Edit"
    Then the response status code should be 200

  Scenario: Test that blackbox login works
    Given I am logged in as "Sparks Editor" with password "editorpass"
    When I visit "/user"
    Then I should see the heading "Sparks Editor"
    
  @api
  Scenario: Log in as superadmin
    Given I am logged in as the superuser
    And I visit "/admin/modules"
    Then the response status code should be 200
